---
name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.22
      - uses: goreleaser/goreleaser-action@v2
        with:
          args: build --snapshot --clean

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.22
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.37
          skip-go-installation: true
          args: --enable-all -D exhaustivestruct
